# Generated by Django 2.1.2 on 2018-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peixe',
            name='fase_atual',
            field=models.CharField(choices=[(1, 'Alevinos'), (2, 'Recria'), (3, 'Engorda')], default='Alevinos', max_length=15, verbose_name='Fase Atual de Criação'),
        ),
        migrations.AlterField(
            model_name='peixe',
            name='tempo_medio_crescimento',
            field=models.PositiveIntegerField(default=0, verbose_name='Tempo Médio de Crescimento(Anos)'),
        ),
    ]
