# Generated by Django 2.1.2 on 2018-10-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixes', '0002_auto_20181020_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='peixe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='peixes/images', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='peixe',
            name='fase_atual',
            field=models.IntegerField(choices=[(1, 'Alevinos'), (2, 'Recria'), (3, 'Engorda')], default=1, verbose_name='Fase Atual de Criação'),
        ),
    ]
