# Generated by Django 2.1.2 on 2018-10-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixes', '0003_auto_20181020_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='peixe',
            name='caracteristica',
            field=models.TextField(default=1, verbose_name='Característica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peixe',
            name='descricao',
            field=models.CharField(default='peixe de agua doce', max_length=150, verbose_name='Breve Descricao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peixe',
            name='distrib_geograf',
            field=models.TextField(default='Rios', verbose_name='Distribuição Geográfica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peixe',
            name='reproducao',
            field=models.TextField(default='Em Área Limpa', verbose_name='Reprodução'),
            preserve_default=False,
        ),
    ]
