# Generated by Django 2.1.2 on 2018-10-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100, verbose_name='Nome do Proprietário')),
                ('cpf', models.CharField(max_length=16, verbose_name='CPF do Proprietário')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
            },
        ),
    ]
