# Generated by Django 2.1.2 on 2018-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='cep',
            field=models.CharField(default='', max_length=15, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='proprietario',
            name='cidade',
            field=models.CharField(default='', max_length=45, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='proprietario',
            name='estado',
            field=models.CharField(default='', max_length=25, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='proprietario',
            name='logradouro',
            field=models.CharField(default='', max_length=100, verbose_name='Logradouro'),
        ),
    ]
