# Generated by Django 2.1.2 on 2018-10-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Name')),
                ('responsavel', models.CharField(max_length=150, verbose_name='Responsável')),
                ('numero_peixes', models.IntegerField(verbose_name='Número de Peixes')),
                ('especie', models.CharField(max_length=150, verbose_name='Espécie')),
                ('tamanho', models.FloatField(verbose_name='Tamanho do tanque (m3)')),
                ('material', models.CharField(max_length=150, verbose_name='Material do tanque')),
                ('manutencao', models.DateField(verbose_name='Data da Manutenção')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('slug', models.CharField(max_length=250, verbose_name='Atalho')),
            ],
            options={
                'verbose_name': 'Tanque',
                'verbose_name_plural': 'Tanques',
                'ordering': ['nome', 'responsavel'],
            },
        ),
    ]
