# Generated by Django 2.1.2 on 2018-10-20 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20181020_1653'),
        ('tanques', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tanque',
            options={'ordering': ['nome', 'proprietario'], 'verbose_name': 'Tanque', 'verbose_name_plural': 'Tanques'},
        ),
        migrations.RemoveField(
            model_name='tanque',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='tanque',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Proprietario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tanque',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peixes.Peixe'),
        ),
    ]
